image:
  repository: ghcr.io/gtsteffaniak/filebrowser
  tag: 0.8.0-beta
  pullPolicy: IfNotPresent

securityContext:
  runAsUser: 1000

extraPodLabels: {}

serviceAccount:
  name: default  

resources:
  requests:
    cpu: 300m
    memory: 150Mi
  limits:
    cpu: 500m
    memory: 300Mi

ingress:
  enabled: false
  class: nginx
  host: filebrowser.example.com
  certSecret: secret
  maxBodySize: 100M # 0 for unlimited

persistence:
  enabled: true
  keep: true
  storageClass: standard
  accessMode: ReadWriteOnce
  configSize: 1Gi
  dataSize: 1Gi

extraVolumes: []
extraVolumeMounts: []

#adminPassword: overrides the FILEBROWSER_ADMIN_PASSWORD env var. 
adminPassword:
  #passwordLength: for admin. Also set the minLength under config
  passwordLength: 20
  passwordOverride: ""  # Leave empty to auto-generate

#config: contains application config file which will be mounted to the pod
#config: these defaults are copied from https://github.com/gtsteffaniak/filebrowser/wiki/Full-Config-Example
config:
  server:
    numImageProcessors: 1                   # number of concurrent image processing jobs used to create previews, default is number of cpu cores available.
    socket: ""                              # socket to listen on
    tlsKey: ""                              # path to TLS key
    tlsCert: ""                             # path to TLS cert
    disablePreviews: false                  # disable all previews thumbnails, simple icons will be used
    disablePreviewResize: false             # disable resizing of previews for faster loading over slow connections
    disableTypeDetectionByHeader: false     # disable type detection by header, useful if filesystem is slow.
    port: 8080                              # port to listen on
    baseURL: /                              # base URL for the server, the subpath that the server is running on.
    logging:
      - levels: ""                          # separated list of log levels to enable. (eg. "info|warning|error|debug")
        apiLevels: ""                       # separated list of log levels to enable for the API. (eg. "info|warning|error")
        output: "stdout"                    # output location. (eg. "stdout" or "path/to/file.log")
        noColors: false                     # disable colors in the output
        json: false                         # output in json format, currently not supported
        utc: false                          # use UTC time in the output instead of local time
    debugMedia: false                       # output ffmpeg stdout for media integration -- careful can produces lots of output!
    database: /home/filebrowser/data/database.db  # path to the database file. Default under data PVC to persist
    sources:                                #  validate:required,dive
      - path: /data                         # file system path. (Can be relative)  validate:required
        name: "Data"                        # display name
        config:
          indexingIntervalMinutes: 0        # optional manual overide interval in seconds to re-index the source
          disableIndexing: false            # disable the indexing of this source
          maxWatchers: 0                    # number of concurrent watchers to use for this source, currently not supported
          neverWatchPaths: []
          exclude:                          # exclude files and folders from indexing, if include is not set
            hidden: false                   # exclude hidden files and folders.
            ignoreZeroSizeFolders: false    # ignore folders with 0 size
            filePaths: []
            folderPaths: []
            fileNames: []
            folderNames: []
            fileEndsWith: []
            folderEndsWith: []
          include:                          # include files and folders from indexing, if exclude is not set
            rootFolders: []
            rootFiles: []
          defaultUserScope: "/"             # default "/" should match folders under path
          defaultEnabled: false             # should be added as a default source for new users?
          createUserDir: false              # create a user directory for each user
    externalUrl: ""                         # used by share links if set
    internalUrl: ""                         # used by integrations if set, this is the url that an integration service will use to communicate with filebrowser
    cacheDir: "tmp"                         # path to the cache directory, used for thumbnails and other cached files
    maxArchiveSize: 50                      # max pre-archive combined size of files/folder that are allowed to be archived (in GB)
  auth:
    tokenExpirationHours: 2                 # the number of hours until the token expires. Default is 2 hours.
    methods:
      proxy:                                #  validate:omitempty
        enabled: false
        createUser: false                   # create user if not exists
        header: ""                          # required header to use for authentication. Security Warning: FileBrowser blindly accepts the header value as username.
        logoutRedirectUrl: ""               # if provider logout url is provided, filebrowser will also redirect to logout url. Custom logout query params are respected.
      noauth: false                         # if set to true, overrides all other auth methods and disables authentication
      password:                             #  validate:omitempty
        enabled: true
        minLength: 20                       # minimum pasword length required.  validate:omitempty,min=5
        signup: false                       # allow signups on login page if enabled -- not secure.  validate:omitempty
        recaptcha:                          # recaptcha config, only used if signup is enabled  validate:omitempty
          host: ""                          #  validate:required
          key: ""                           #  validate:required
          secret: ""                        #  validate:required
        enforcedOtp: false                  # if set to true, TOTP is enforced for all password users users. Otherwise, users can choose to enable TOTP.
      oidc:                                 #  validate:omitempty
        enabled: false                      # whether to enable OIDC authentication
        clientId: ""                        # client id of the OIDC application
        clientSecret: ""                    # client secret of the OIDC application
        issuerUrl: ""                       # authorization URL of the OIDC provider
        scopes: "openid email profile"      # scopes to request from the OIDC provider
        userIdentifier: "preferred_username" # the field value to use as the username. Default is "preferred_username", can also be "email" or "username", or "phone"
        disableVerifyTLS: false             # disable TLS verification for the OIDC provider. This is insecure and should only be used for testing.
        logoutRedirectUrl: ""               # if provider logout url is provided, filebrowser will also redirect to logout url. Custom logout query params are respected.
        createUser: false                   # create user if not exists
        adminGroup: ""                      # if set, users in this group will be granted admin privileges.
        groupsClaim: "groups"               # the JSON field name to read groups from. Default is "groups"
    key: ""                                 # the key used to sign the JWT tokens. If not set, a random key will be generated.
    adminUsername: "admin"                  # the username of the admin user. If not set, the default is "admin".
    adminPassword: "admin"                  # the password of the admin user. If not set, the default is "admin".
    totpSecret: ""                          # secret used to encrypt TOTP secrets
  frontend:
    name: "FileBrowser Quantum"             # display name
    disableDefaultLinks: false              # disable default links in the sidebar
    disableUsedPercentage: false            # disable used percentage for the sources in the sidebar
    externalLinks:
      - text: "(untracked)"                 # the text to display on the link  validate:required
        title: "untracked"                  # the title to display on hover
        url: "https://github.com/gtsteffaniak/filebrowser/releases/" # the url to link to  validate:required
      - text: "Help"                        # the text to display on the link  validate:required
        title: ""                           # the title to display on hover
        url: "https://github.com/gtsteffaniak/filebrowser/wiki" # the url to link to  validate:required
      - text: "Chart (Softwaredam)"
        title: "Chart (Softwaredam)"
        url: "https://github.com/Softwaredam/filebrowser-chart/"
    disableNavButtons: false                # disable the nav buttons in the sidebar
    styling:
      customCSS: ""                         # if a valid path to a css file is provided, it will be applied for all users. (eg. "reduce-rounded-corners.css")
      lightBackground: "white"              # specify a valid CSS color property value to use as the background color in light mode
      darkBackground: "#141D24"             # Specify a valid CSS color property value to use as the background color in dark mode
      customThemes:                         # A list of custom css files that each user can select to override the default styling. if "default" is key name then it will be the default option.
        default:
          description: The default theme
          css: ""
  userDefaults:
    editorQuickSave: false                  # show quick save button in editor
    hideSidebarFileActions: false           # hide the file actions in the sidebar
    disableQuickToggles: false              # disable the quick toggles in the sidebar
    disableSearchOptions: false             # disable the search options in the search bar
    stickySidebar: true                     # keep sidebar open when navigating
    darkMode: true                          # should dark mode be enabled
    locale: "en"                            # language to use: eg. de, en, or fr
    viewMode: "normal"                      # view mode to use: eg. normal, list, grid, or compact
    singleClick: false                      # open directory on single click, also enables middle click to open in new tab
    showHidden: false                       # show hidden files in the UI. On windows this includes files starting with a dot and windows hidden files
    dateFormat: false                       # when false, the date is relative, when true, the date is an exact timestamp
    gallerySize: 3                          # 0-9 - the size of the gallery thumbnails
    themeColor: "var(--blue)"               # theme color to use: eg. #ff0000, or var(--red), var(--purple), etc
    quickDownload: false                    # show icon to download in one click
    disablePreviewExt: ""                   # comma separated list of file extensions to disable preview for
    disableViewingExt: ""                   # comma separated list of file extensions to disable viewing for
    lockPassword: false                     # disable the user from changing their password
    disableSettings: false                  # disable the user from viewing the settings page
    preview:
      disableHideSidebar: false
      highQuality: false
      image: false
      video: false
      motionVideoPreview: false
      office: false
      popup: false
      autoplayMedia: false
    permissions:
      api: false
      admin: false
      modify: false
      share: false
      realtime: false
    loginMethod: "password"                 # login method to use: eg. password, proxy, oidc
    disableUpdateNotifications: false       # disable update notifications banner for admin users
    deleteWithoutConfirming: false          # delete files without confirmation
    fileLoading:                            # upload and download settings
      maxConcurrentUpload: 10
      uploadChunkSizeMb: 10
    disableOfficePreviewExt: ""             # deprecated: use disablePreviewExt instead
    disableOnlyOfficeExt: ""                # list of file extensions to disable onlyoffice editor for
    customTheme: ""                         # Name of theme to use chosen from custom themes config.
  integrations:
    office:                                 #  validate:omitempty
      url: ""                               # The URL to the OnlyOffice Document Server, needs to be accessible to the user.  validate:required
      internalUrl: ""                       # An optional internal address that the filebrowser server can use to communicate with the OnlyOffice Document Server, could be useful to bypass proxy.
      secret: ""                            #  validate:required
    media:                                  #  validate:omitempty
      ffmpegPath: ""                        # path to ffmpeg directory with ffmpeg and ffprobe (eg. /usr/local/bin)
