---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-filebrowser-quantum
  labels:
    release: {{ .Release.Name }}
    app: filebrowser-quantum
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}