{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    {{- if .Values.persistence.keep }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.persistence.data.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ .Release.Name }}-filebrowser-quantum-data
  labels:
    release: {{ .Release.Name }}
    app: filebrowser-quantum
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode | default .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  storageClassName: {{ .Values.persistence.data.storageClass | default .Values.persistence.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    {{- if .Values.persistence.keep }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.persistence.config.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ .Release.Name }}-filebrowser-quantum-config
  labels:
    release: {{ .Release.Name }}
    app: filebrowser-quantum
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode | default .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
  storageClassName: {{ .Values.persistence.config.storageClass | default .Values.persistence.storageClass }}
{{- end }}
