---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-filebrowser-quantum
  labels:
    release: {{ .Release.Name }}
    app: filebrowser-quantum
type: Opaque
stringData:
  FILEBROWSER_ADMIN_PASSWORD: {{- if .Values.adminPassword.passwordOverride }}
    {{ .Values.adminPassword.passwordOverride }}
  {{- else }}
    {{- $length := int (.Values.adminPassword.passwordLength | default 20) }}
    {{- $chars := splitList "" "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789#%^-" }}
    {{- $charCount := len $chars }}
    {{- $password := "" }}
    {{- range $i, $e := until $length }}
      {{- $index := randInt 0 $charCount }}
      {{- $password = printf "%s%s" $password (index $chars $index) }}
    {{- end }}
    {{ $password }}
  {{- end }}