{{- if not .Values.secret.existingSecret }}
{{- $secretName := include "filebrowser-quantum.fullname" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "filebrowser-quantum.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret.adminPassword }}
  FILEBROWSER_ADMIN_PASSWORD: {{ .Values.secret.adminPassword | quote }}
  {{- else if and $existingSecret (index $existingSecret.data "FILEBROWSER_ADMIN_PASSWORD") }}
  FILEBROWSER_ADMIN_PASSWORD: {{ index $existingSecret.data "FILEBROWSER_ADMIN_PASSWORD" | b64dec | quote }}
  {{- else }}
  FILEBROWSER_ADMIN_PASSWORD: {{ randAlphaNum (int .Values.secret.adminPasswordLength) | quote }}
  {{- end }}
  {{- if .Values.secret.jwtSecret }}
  FILEBROWSER_JWT_TOKEN_SECRET: {{ .Values.secret.jwtSecret | quote }}
  {{- else if and $existingSecret (index $existingSecret.data "FILEBROWSER_JWT_TOKEN_SECRET") }}
  FILEBROWSER_JWT_TOKEN_SECRET: {{ index $existingSecret.data "FILEBROWSER_JWT_TOKEN_SECRET" | b64dec | quote }}
  {{- else }}
  FILEBROWSER_JWT_TOKEN_SECRET: {{ randAlphaNum 32 | quote }}
  {{- end }}
  {{- if .Values.secret.totpSecret }}
  FILEBROWSER_TOTP_SECRET: {{ .Values.secret.totpSecret | quote }}
  {{- end }}
  {{- if .Values.secret.oidcClientId }}
  FILEBROWSER_OIDC_CLIENT_ID: {{ .Values.secret.oidcClientId | quote }}
  {{- end }}
  {{- if .Values.secret.oidcClientSecret }}
  FILEBROWSER_OIDC_CLIENT_SECRET: {{ .Values.secret.oidcClientSecret | quote }}
  {{- end }}
  {{- if .Values.secret.onlyofficeSecret }}
  FILEBROWSER_ONLYOFFICE_SECRET: {{ .Values.secret.onlyofficeSecret | quote }}
  {{- end }}
  {{- if .Values.secret.recaptchaSecret }}
  FILEBROWSER_RECAPTCHA_SECRET: {{ .Values.secret.recaptchaSecret | quote }}
  {{- end }}
{{- end }}
